// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyDuAnCongTrinhXayDung.Data;

#nullable disable

namespace QuanLyDuAnCongTrinhXayDung.Migrations
{
    [DbContext(typeof(QLDACTXDDbContext))]
    partial class QLDACTXDDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyDuAnCongTrinhXayDung.Data.BangLuong", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Nam")
                        .HasColumnType("int");

                    b.Property<int>("NhanVienID")
                        .HasColumnType("int");

                    b.Property<int>("SoNgayCong")
                        .HasColumnType("int");

                    b.Property<int>("Thang")
                        .HasColumnType("int");

                    b.Property<decimal>("ThucLinh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongPhuCap")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("NhanVienID");

                    b.ToTable("BangLuong");
                });

            modelBuilder.Entity("QuanLyDuAnCongTrinhXayDung.Data.CongViec", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("TenCongViec")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("CongViec");
                });

            modelBuilder.Entity("QuanLyDuAnCongTrinhXayDung.Data.DuAn", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DiaDiem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KhachHangID")
                        .HasColumnType("int");

                    b.Property<int>("LoaiDuAnID")
                        .HasColumnType("int");

                    b.Property<decimal>("NganSach")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<int>("NhaDauTuID")
                        .HasColumnType("int");

                    b.Property<string>("TenDuAn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("KhachHangID");

                    b.HasIndex("LoaiDuAnID");

                    b.HasIndex("NhaDauTuID");

                    b.ToTable("DuAn");
                });

            modelBuilder.Entity("QuanLyDuAnCongTrinhXayDung.Data.KhachHang", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaSoThue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiDaiDien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenCongTy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("QuanLyDuAnCongTrinhXayDung.Data.LoaiDuAn", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("LoaiDuAn");
                });

            modelBuilder.Entity("QuanLyDuAnCongTrinhXayDung.Data.NhaDauTu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaSoThue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNhaDauTu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("NhaDauTu");
                });

            modelBuilder.Entity("QuanLyDuAnCongTrinhXayDung.Data.NhanVien", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ChuyenMon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoVaTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LuongCoBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("QuyenHan")
                        .HasColumnType("bit");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("QuanLyDuAnCongTrinhXayDung.Data.NhatKyCongTrinh", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("DuAnID")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayGhi")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDungCongViec")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("DuAnID");

                    b.ToTable("NhatKyCongTrinh");
                });

            modelBuilder.Entity("QuanLyDuAnCongTrinhXayDung.Data.PhanCong", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CongViecID")
                        .HasColumnType("int");

                    b.Property<int>("DuAnID")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<int>("NhanVienID")
                        .HasColumnType("int");

                    b.Property<int>("PhanTramHoanThanh")
                        .HasColumnType("int");

                    b.Property<decimal?>("PhuCap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CongViecID");

                    b.HasIndex("DuAnID");

                    b.HasIndex("NhanVienID");

                    b.ToTable("PhanCong");
                });

            modelBuilder.Entity("QuanLyDuAnCongTrinhXayDung.Data.VatTu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenVatTu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("VatTu");
                });

            modelBuilder.Entity("QuanLyDuAnCongTrinhXayDung.Data.VatTuChiTiet", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("DonGiaTaiThoiDiem")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DuAnID")
                        .HasColumnType("int");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayCapPhat")
                        .HasColumnType("datetime2");

                    b.Property<double>("SoLuong")
                        .HasColumnType("float");

                    b.Property<int>("VatTuID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("DuAnID");

                    b.HasIndex("VatTuID");

                    b.ToTable("VatTuChiTiet");
                });

            modelBuilder.Entity("QuanLyDuAnCongTrinhXayDung.Data.BangLuong", b =>
                {
                    b.HasOne("QuanLyDuAnCongTrinhXayDung.Data.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("NhanVienID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QuanLyDuAnCongTrinhXayDung.Data.DuAn", b =>
                {
                    b.HasOne("QuanLyDuAnCongTrinhXayDung.Data.KhachHang", "KhachHang")
                        .WithMany("DuAn")
                        .HasForeignKey("KhachHangID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyDuAnCongTrinhXayDung.Data.LoaiDuAn", "LoaiDuAn")
                        .WithMany("DuAn")
                        .HasForeignKey("LoaiDuAnID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyDuAnCongTrinhXayDung.Data.NhaDauTu", "NhaDauTu")
                        .WithMany("DuAn")
                        .HasForeignKey("NhaDauTuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("LoaiDuAn");

                    b.Navigation("NhaDauTu");
                });

            modelBuilder.Entity("QuanLyDuAnCongTrinhXayDung.Data.NhatKyCongTrinh", b =>
                {
                    b.HasOne("QuanLyDuAnCongTrinhXayDung.Data.DuAn", "DuAn")
                        .WithMany()
                        .HasForeignKey("DuAnID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DuAn");
                });

            modelBuilder.Entity("QuanLyDuAnCongTrinhXayDung.Data.PhanCong", b =>
                {
                    b.HasOne("QuanLyDuAnCongTrinhXayDung.Data.CongViec", "CongViec")
                        .WithMany("PhanCong")
                        .HasForeignKey("CongViecID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyDuAnCongTrinhXayDung.Data.DuAn", "DuAn")
                        .WithMany("PhanCong")
                        .HasForeignKey("DuAnID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyDuAnCongTrinhXayDung.Data.NhanVien", "NhanVien")
                        .WithMany("PhanCong")
                        .HasForeignKey("NhanVienID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CongViec");

                    b.Navigation("DuAn");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QuanLyDuAnCongTrinhXayDung.Data.VatTuChiTiet", b =>
                {
                    b.HasOne("QuanLyDuAnCongTrinhXayDung.Data.DuAn", "DuAn")
                        .WithMany("VatTuChiTiet")
                        .HasForeignKey("DuAnID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyDuAnCongTrinhXayDung.Data.VatTu", "VatTu")
                        .WithMany("ChiPhiVatTu")
                        .HasForeignKey("VatTuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DuAn");

                    b.Navigation("VatTu");
                });

            modelBuilder.Entity("QuanLyDuAnCongTrinhXayDung.Data.CongViec", b =>
                {
                    b.Navigation("PhanCong");
                });

            modelBuilder.Entity("QuanLyDuAnCongTrinhXayDung.Data.DuAn", b =>
                {
                    b.Navigation("PhanCong");

                    b.Navigation("VatTuChiTiet");
                });

            modelBuilder.Entity("QuanLyDuAnCongTrinhXayDung.Data.KhachHang", b =>
                {
                    b.Navigation("DuAn");
                });

            modelBuilder.Entity("QuanLyDuAnCongTrinhXayDung.Data.LoaiDuAn", b =>
                {
                    b.Navigation("DuAn");
                });

            modelBuilder.Entity("QuanLyDuAnCongTrinhXayDung.Data.NhaDauTu", b =>
                {
                    b.Navigation("DuAn");
                });

            modelBuilder.Entity("QuanLyDuAnCongTrinhXayDung.Data.NhanVien", b =>
                {
                    b.Navigation("PhanCong");
                });

            modelBuilder.Entity("QuanLyDuAnCongTrinhXayDung.Data.VatTu", b =>
                {
                    b.Navigation("ChiPhiVatTu");
                });
#pragma warning restore 612, 618
        }
    }
}
